export type ApiEndpoint = {
  method: "get" | "post" | "patch" | "delete";
  path: string;
};

export type ApiRouteContract = {
  method: "GET" | "POST" | "PATCH" | "DELETE";
  path: string;
};

export const apiRouteManifest: ApiRouteContract[] = [
  { method: "POST", path: "/auth/login" },
  { method: "POST", path: "/auth/logout" },
  { method: "GET", path: "/auth/me" },
  { method: "GET", path: "/admin/dashboard" },
  { method: "GET", path: "/reports/filters" },
  { method: "GET", path: "/calls/search" },
  { method: "GET", path: "/reports/summary" },
  { method: "GET", path: "/reports/staff" },
  { method: "GET", path: "/reports/categories" },
  { method: "GET", path: "/reports/export" },
  { method: "GET", path: "/call-options" },
  { method: "POST", path: "/call-options" },
  { method: "PATCH", path: "/call-options" },
  { method: "PATCH", path: "/call-options/:id" },
  { method: "GET", path: "/calls/assignees" },
  { method: "GET", path: "/calls" },
  { method: "POST", path: "/calls" },
  { method: "GET", path: "/calls/matches" },
  { method: "GET", path: "/calls/:id" },
  { method: "PATCH", path: "/calls/:id" },
  { method: "POST", path: "/calls/:id/notes" },
  { method: "PATCH", path: "/calls/:id/assign" },
  { method: "PATCH", path: "/calls/:id/status" },
  { method: "POST", path: "/calls/:id/resolve" },
  { method: "POST", path: "/calls/:id/reopen" },
  { method: "GET", path: "/permissions" },
  { method: "GET", path: "/roles" },
  { method: "POST", path: "/roles" },
  { method: "PATCH", path: "/roles/:id" },
  { method: "PATCH", path: "/roles/:id/permissions" },
  { method: "GET", path: "/settings" },
  { method: "GET", path: "/settings/security" },
  { method: "PATCH", path: "/settings/security" },
  { method: "PATCH", path: "/settings" },
  { method: "GET", path: "/settings/options/:type" },
  { method: "POST", path: "/settings/options/:type" },
  { method: "PATCH", path: "/settings/options/:type/:id" },
  { method: "GET", path: "/users/options" },
  { method: "GET", path: "/users" },
  { method: "POST", path: "/users" },
  { method: "PATCH", path: "/users/:id" },
  { method: "DELETE", path: "/users/:id" },
  { method: "POST", path: "/users/:id/restore" },
  { method: "GET", path: "/logs" },
  { method: "GET", path: "/notifications" },
  { method: "PATCH", path: "/notifications/:id/read" },
];

export const protectedApiEndpoints: ApiEndpoint[] = [
  { method: "get", path: "/admin/dashboard" },
  { method: "post", path: "/auth/logout" },
  { method: "get", path: "/auth/me" },
  { method: "get", path: "/call-options" },
  { method: "post", path: "/call-options" },
  { method: "patch", path: "/call-options" },
  { method: "patch", path: "/call-options/test-id" },
  { method: "get", path: "/calls/assignees" },
  { method: "get", path: "/calls" },
  { method: "post", path: "/calls" },
  { method: "get", path: "/calls/matches" },
  { method: "get", path: "/calls/test-id" },
  { method: "patch", path: "/calls/test-id" },
  { method: "post", path: "/calls/test-id/notes" },
  { method: "patch", path: "/calls/test-id/assign" },
  { method: "patch", path: "/calls/test-id/status" },
  { method: "post", path: "/calls/test-id/resolve" },
  { method: "post", path: "/calls/test-id/reopen" },
  { method: "get", path: "/logs" },
  { method: "get", path: "/notifications" },
  { method: "patch", path: "/notifications/test-id/read" },
  { method: "get", path: "/reports/filters" },
  { method: "get", path: "/calls/search" },
  { method: "get", path: "/reports/summary" },
  { method: "get", path: "/reports/staff" },
  { method: "get", path: "/reports/categories" },
  { method: "get", path: "/reports/export" },
  { method: "get", path: "/permissions" },
  { method: "get", path: "/roles" },
  { method: "post", path: "/roles" },
  { method: "patch", path: "/roles/test-id" },
  { method: "patch", path: "/roles/test-id/permissions" },
  { method: "get", path: "/settings" },
  { method: "get", path: "/settings/security" },
  { method: "patch", path: "/settings/security" },
  { method: "patch", path: "/settings" },
  { method: "get", path: "/settings/options/status" },
  { method: "post", path: "/settings/options/status" },
  { method: "patch", path: "/settings/options/status/test-id" },
  { method: "get", path: "/users/options" },
  { method: "get", path: "/users" },
  { method: "post", path: "/users" },
  { method: "patch", path: "/users/test-id" },
  { method: "delete", path: "/users/test-id" },
  { method: "post", path: "/users/test-id/restore" },
];
